### PR TITLE
Fix IOS routing table static route attributes

### LINKED ISSUE #535: Batfish sets admin distance as 1 for Null0 route instead of 0 as set by Cisco IOS
ENV  lhr-leaf-01 vrf:default net:10.1.1.0/24 nhip:AUTO/NONE(-1l) nhint:Null0 nhnode:N/A admin:0 cost:0 tag:none prot:static
BAT  lhr-leaf-01 vrf:default net:10.1.1.0/24 nhip:AUTO/NONE(-1l) nhint:null_interface nhnode:N/A admin:1 cost:0 tag:none prot:static

### PR DESCRIPTION
**Pull request by arifogel**
- Fix #535 
- Generalize and clean up testrig junit tests

### CODE REVIEW

File: projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java [hunk 1]
```diff
@@ -209,4 +257,15 @@ public static Batfish getBatfish(
     }
     return initBatfish(configurations, tempFolder);
   }
+
+  private static SortedMap<String, String> readTestrigResources(
+      String testrigResourcePrefix, String subfolder, String[] filenames) {
```
Comment (dhalperi) [inline projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java]: suggest making filenames a `String...` so that you can use the function more manually in the future.

File: projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java [hunk 2]
```diff
@@ -149,9 +149,19 @@ public void testApplySourceNatInvalidAclThrows() {
   public void testIbgpRejectOwnAs() throws IOException {
     String testrigName = "ibgp-reject-own-as";
     String[] configurationNames = new String[] {"r1", "r2a", "r2b"};
+    String[] bgpTableNames = new String[] {};
+    String[] hostFilenames = new String[] {};
+    String[] iptablesFilenames = new String[] {};
+    String[] routingTableNames = new String[] {};
```
Comment (dhalperi) [inline projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java]: suggest general inlining of these variables throughout PR, (if you feel like it). If only used once, may make code more readable.
